### ISSUE TITLE
Setup node and base react environments

### ISSUE THREAD

**Issue by frattezi** [fmagesty/primeiro-ciclo-de-mentoria#14]
First, you have to guarantee that you have installed in you local machine:

- nodejs
- npm
- yarn | `npm install -g yarn`

---

- Setup **Babel** , follow this [docs](https://babeljs.io/docs/en/)
- Setup **Webpack**, follow this [docs](https://webpack.js.org/concepts/)
- Setup **Hot Reload**, [package](https://www.npmjs.com/package/react-hot-loader), [docs](https://blog.logrocket.com/setup-react-hotloader-in-10-minutes-3175dfdbf38a/)

Also, call for Lucca's help when understanding and setting up both of the above.

To be considered done:

- When `yarn start` (or your local development startup command ) works!

**Comment by frattezi** [comment]
Your app does not contain any react hot reload binds or its functionality.

Remember, the tasks are describing everything you need to do in order for delivery. If we do not complete the task objectives it can create future bugs, and certain expected functionalities would not be implemented, creating errors for other developers.

**Comment by fmagesty** [comment]
it seems that hot loader will be replaced "React-Hot-Loader is expected to be replaced by React Fast Refresh. Please remove React-Hot-Loader if Fast Refresh is currently supported on your environment.

React Native - supports Fast Refresh since 0.61.
parcel 2 - supports Fast Refresh since alpha 3.
webpack - supports Fast Refresh using a plugin.
other bundler - no support yet, use React-Hot-Loader"


so I'm going to use fast refresh instead

**Comment by fmagesty** [comment]
source: https://www.npmjs.com/package/react-hot-loader

**Comment by fmagesty** [comment]
done. I'm using React Refresh Webpack Plugin

**Comment by fmagesty** [comment]
repo: https://github.com/fmagesty/base-projects/tree/react-javascript

**Comment by frattezi** [comment]
Nice, good argumentation and documenting process!


Did you understand this logic?
```javascript
  plugins: [
    htmlPlugin,
    isDevelopment && new webpack.HotModuleReplacementPlugin(),
    isDevelopment && new ReactRefreshWebpackPlugin(),
```
